# -*- coding: utf-8 -*-
"""conversor_nf_kmz-para-csv_xlsx

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nFz3YjM1bCD7i2iFxcg5YhrPldsGsjnT
"""
import os
import xmltodict
import pandas as pd

lista_arquivos = os.listdir('https://github.com/caioyl/python_projetos/tree/main/conversor_nf_para_csv/nfs')
colunas = ['numero_nota','empresa_emissora','nome_cliente','bairro','rua','numero','complemento','peso']
valores = []


def pegar_infos(nome_arquivo, valores):
  with open(f'https://github.com/caioyl/python_projetos/tree/main/conversor_nf_para_csv/nfs/{nome_arquivo}','rb') as arquivo_xml:
    dic_arquivo = xmltodict.parse(arquivo_xml)
    if 'NFe' in dic_arquivo:
      infos_nf = dic_arquivo['NFe']['infNFe']
    else:
      infos_nf = dic_arquivo['nfeProc']['NFe']['infNFe']
    numero_nota = infos_nf['@Id']
    empresa_emissora = infos_nf['emit']['xNome']
    nome_cliente = infos_nf['dest']['xNome']
    endereço = infos_nf['dest']['enderDest']
    bairro = endereço['xBairro']
    rua = endereço['xLgr']
    numero = endereço['nro']
    if 'xCpl' in endereço:
      complemento = endereço['xCpl']
    else:
      complemento = 'Não informado'
    if 'vol' in infos_nf['transp']:
      pesoB = infos_nf['transp']['vol']['pesoB']
    else:
      pesoB = 'Não informado'
    print('\n')
    valores.append([numero_nota, empresa_emissora, nome_cliente,bairro, rua, numero, complemento, pesoB])

for arquivo in lista_arquivos:
  pegar_infos(arquivo,valores)

tabela = pd.DataFrame(columns=colunas,data=valores)
tabela.to_excel('NotasFiscais.xlsx',index=False)